### ISSUE TITLE
forge batch

### ISSUE THREAD

**Issue by cenwadike** [tokamak-network/tokamak-sybil-resistance#6]
- When the coordinator calls the forging function, the L2Txs data is sent as input to the smart contract function. This data can be retrieved by querying the arguments of the function call.

check [specs](https://www.notion.so/tokamak/SYB-Specification-1c91518ee02a424a894553e8820f9cd2#7e80030744504827b5f486891bd42f1c) for more details

**Comment by demis1997** [comment]
We are working on L1 for now and I have added forgebatch for L1 along with tests here: https://github.com/tokamak-network/tokamak-sybil-resistance/tree/smartcontract 
Now I am increasing test coverage and making use of helper constants
